# Generated by Django 3.1.3 on 2021-05-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20210503_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='user',
        ),
    ]
